version: '3'

services:
  mongo:
    image: mongo:4.4.2-bionic
    command: --logpath /dev/null
    restart: on-failure
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:     pg
      POSTGRES_PASSWORD: pg

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

networks:
  default:

