version: '3'

services:
  mongo:
    image: mongo:4.4.2-bionic
    command: --logpath /dev/null
    restart: on-failure
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
     - 6379:6379

networks:
  default:

